###
# @http
GET http://localhost:5000/http-send/test-http


###
# @mq
GET http://localhost:5000/mq-send/test-mq

###
# @mqresponse
GET http://localhost:5000/mq-send-and-reply/test-mq-response
